services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend

  backend:
    build: ./backend
    # Redisに接続するための環境変数を追加
    environment:
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./database:/app/database
    # Redisコンテナが起動してからバックエンドが起動するように設定
    depends_on:
      - redis

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules

  # Redisサービスを新規追加
  redis:
    image: redis:alpine
    restart: always