services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    restart: unless-stopped
  backend:
    build: ./backend
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    restart: unless-stopped
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    restart: unless-stopped
  redis:
    image: redis:alpine
    restart: unless-stopped